export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR =  'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REQUEST_ALL_MOVIES = "REQUEST_ALL_MOVIES";
export const RECEIVE_ALL_MOVIES = "RECEIVE_ALL_MOVIES";
export const REQUEST_MOVIE = "REQUEST_MOVIE";
export const RECEIVE_MOVIE = "RECEIVE_MOVIE";
export const MOVIE_RATED = "MOVIE_RATED";